services:
  aicacia-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - aicacia-postgres


  aicacia-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aicacia_db
    ports:
      - "5432:5432"
    volumes:
      - aicacia_postgres_data:/var/lib/postgresql/data

volumes:
  aicacia_postgres_data: