services:
  aicacia-postgres:
    image: postgres:17
    container_name: aicacia-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: aicacia_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  aicacia-api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: aicacia-api-dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /app/__pycache__
    depends_on:
      - aicacia-postgres
    command: ["uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  aicacia-webapp-dev:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    container_name: aicacia-webapp-dev
    ports:
      - "5173:5173"
    volumes:
      - ./webapp:/webapp
      - /webapp/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    command: ["yarn", "dev", "--host", "0.0.0.0"]

volumes:
  pg_data_dev: 