"""create a table for thread_message_feedback

Revision ID: 6dc380cca19a
Revises: 4874ba1a2ac8
Create Date: 2024-11-25 22:49:04.917772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dc380cca19a'
down_revision: Union[str, None] = '4874ba1a2ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_message_feedback',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('feeddback_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id', 'message_id'], ['thread_messages.thread_id', 'thread_messages.message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('thread_id', 'message_id', 'feeddback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_message_feedback')
    # ### end Alembic commands ###
