"""adding textual_representation

Revision ID: cc42e6051b28
Revises: 7767160a0bb6
Create Date: 2025-12-10 11:12:29.623568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc42e6051b28'
down_revision: Union[str, None] = '7767160a0bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'textual_representation',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('doc_id', sa.Uuid(), nullable=False),
        sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('parser', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['doc_id'], ['sourced_documents.doc_id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.add_column('sourced_documents', sa.Column('current_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sourced_documents', sa.Column('s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sourced_documents', 's3_path')
    op.drop_column('sourced_documents', 'current_status')

    op.drop_table('textual_representation')
    # ### end Alembic commands ###
