dataset:
  max_queries: 3
  path: data/qa_dataset/qa_finetune_dataset.json
methods:
  dense: []
  hybrid:
  - additional_params:
      dense_weight: 0.7
      sparse_weight: 0.3
    batch_size: 32
    device: null
    max_length: 512
    model_id: BAAI/bge-m3
    name: bge-m3-hybrid
    trust_remote_code: true
  reranking: []
  sparse: []
metrics:
  k_values:
  - 1
  - 3
  - 5
  - 10
  - 20
output:
  generate_plots: true
  generate_report: true
  results_dir: results
  save_embeddings: false
performance:
  log_level: INFO
  show_progress: true
