dataset:
  max_queries: null
  path: data/qa_dataset/test_small_dataset.json
methods:
  dense:
  - additional_params: {}
    batch_size: 32
    device: null
    max_length: 512
    model_id: BAAI/bge-m3
    name: bge-m3
    trust_remote_code: true
  hybrid:
  - additional_params:
      dense_weight: 0.7
      sparse_weight: 0.3
    batch_size: 32
    device: null
    max_length: 512
    model_id: BAAI/bge-m3
    name: bge-m3-hybrid
    trust_remote_code: true
  reranking: []
  sparse:
  - additional_params:
      b: 0.75
      k1: 1.2
    batch_size: 32
    device: null
    max_length: 512
    model_id: ''
    name: bm25
    trust_remote_code: true
metrics:
  k_values:
  - 1
  - 3
  - 5
  - 10
  - 20
output:
  generate_plots: true
  generate_report: true
  results_dir: results
  save_embeddings: false
performance:
  log_level: INFO
  show_progress: true
