services:
  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - "./data:/home/jovyan/data"
      - "./extraction:/home/jovyan/extraction"
      - "../extraction:/home/jovyan/aicacia/extraction"
