services:
  grobid:
    platform: linux/amd64
    image: grobid/grobid:0.8.0
    ports:
      - "8070:8070"
  grobid-crf:
    platform: linux/amd64
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
