"""adding a composite constraint

Revision ID: 4874ba1a2ac8
Revises: 7cd9e6312d1c
Create Date: 2024-11-25 22:25:25.085977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4874ba1a2ac8'
down_revision: Union[str, None] = '7cd9e6312d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
