"""add_references_to_thread_messages

Revision ID: ad648a84e7b3
Revises: 7767160a0bb6
Create Date: 2025-12-19 22:21:31.065130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad648a84e7b3'
down_revision: Union[str, None] = '7767160a0bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_messages', sa.Column('references', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread_messages', 'references')
    # ### end Alembic commands ###
