"""add s3_location field

Revision ID: d0a4fad28f8f
Revises: bd4d5e0c13ce
Create Date: 2025-04-22 19:21:20.600537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0a4fad28f8f'
down_revision: Union[str, None] = 'bd4d5e0c13ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_links', sa.Column('s3_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_links', 's3_location')
    # ### end Alembic commands ###
