services:
  aicacia-api:
    build: .
    ports:
      - "8000:8000"
    networks:
      - qdrant_network_ext
      - postgres_network
    depends_on:
      - aicacia-postgres

  aicacia-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aicacia_db
    ports:
      - "5432:5432"
    volumes:
      - aicacia_postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  aicacia_postgres_data:

networks:
  qdrant_network_ext:
    name: qdrant_network
    external: true  # Use existing network created by Qdrant compose
  postgres_network:
    name: postgres_network
    driver: bridge
    
