name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build & Push aicacia-api via buildx
        run: |
          docker buildx build \
          --output type=registry \
          --push \
          --platform linux/amd64 \
          --tag ${{ secrets.ECR_REGISTRY }}/aicacia-api:latest \
          ./api

      - name: Build & Push aicacia-webapp via buildx
        run: |
          docker buildx build \
            --output type=registry \
            --push \
            --platform linux/amd64 \
            --tag ${{ secrets.ECR_REGISTRY }}/aicacia-webapp:latest \
            ./webapp