name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Build docker images
        run: |
          docker images list
          docker system df
          
          docker buildx create --use
          
          docker buildx build --output type=docker,dest=./aicacia-api.tar -t aicacia-api:latest ./api
          
          docker images list
          docker system df  
          
          docker buildx build --output type=docker,dest=./aicacia-webapp.tar -t aicacia-webapp:latest ./webapp
          
          docker images list
          docker system df 

      - name: Copy images and deployment script to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "aicacia-api.tar,aicacia-webapp.tar,infra/deploy.sh"
          target: "/home/ec2-user"

      - name: SSH to EC2, load images and run deployment script
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker rmi -f aicacia-api:latest || true
            docker rmi -f aicacia-webapp:latest || true  
  
            docker load -i /home/ec2-user/aicacia-api.tar
            docker load -i /home/ec2-user/aicacia-webapp.tar
            rm /home/ec2-user/*.tar
            
            chmod +x /home/ec2-user/deploy.sh
            /home/ec2-user/deploy.sh